### ISSUE TITLE
Rules for Implied H-Feed

### ISSUE THREAD

**Issue by dshanske** [microformats/h-feed#1]
Ideally, every feed would be marked up as an h-feed. But barring this, we need to discuss how you should generate an implied h-feed if there isn't an express one.

**Comment by capjamesg** [comment]
I can see a valid use case for this in search engines. Search engines usually accept that not all markup is perfect and adjust for common edge cases. I wonder if there are any examples in the field of lists of h- objects without being marked up with a parent h-feed. How would one determine what constituted a h-feed? Based on the number of posts on the page?

**Comment by dshanske** [comment]
This is defined in https://microformats.org/wiki/h-feed#Implied_h-feed
