### ISSUE TITLE
Add Feed Discovery Section to Specification

### ISSUE THREAD

**Issue by dshanske** [microformats/h-feed#7]
Inspired by https://www.jsonfeed.org/version/1.1/#discovery we should add a discovery section to the spec to cover how to discover an h-feed.

**Comment by capjamesg** [comment]
I would love to see a discovery section that outlines the ways in which a h-feed might be linked to a page (i.e. through a rel="alternate" feed) or how to find a feed on a page.

**Comment by dshanske** [comment]
Often h-feed is the page itself, but if it's not ..

**Comment by dshanske** [comment]
https://microformats.org/wiki/h-feed#Discovery - This was addresed.
