### ISSUE TITLE
How is the actual status?

### ISSUE THREAD

**Issue by math-GH** [microformats/h-feed#9]
Hi,
how is the actual status of h-feed?

Is there a fixed standard?
Any websites that uses already h-feeds?

If there are plenty usable feeds we could implement it into [FreshRSS](https://github.com/FreshRSS/FreshRSS). Help/PRs are always welcome.

**Comment by gRegorLove** [comment]
Hello! The [specification ](https://microformats.org/wiki/h-feed) is in draft status. There are quite a few sites publishing h-feed, including Mastodon profiles. There are some [examples ](https://indieweb.org/h-feed#IndieWeb_Examples)documented on the IndieWeb wiki as well as some [consuming software](https://indieweb.org/h-feed#Consumers_of_H-Feed). 

It would be great to have h-feed support in FreshRSS!

**Comment by gRegorLove** [comment]
Closing for now. Let us know in [microformats chat](https://microformats.org/wiki/irc) if you have questions.
